#%RAML 1.0 Trait
responses:
  
  400:
    description: Bad request
  401:
    description: Not authorised
  403:
    description: Forbidden
  404:
    description: Not found
  405:
    description: Method not allowed 
  415:
    description: Unsupported media type
  429:
    description: Too many requests 
  500:
    description: Server error
  503:
    description: Bad connectivity  